#define IMU IMU_BMI160
#define SECOND_IMU IMU_BMI160
#define BOARD BOARD_WEMOSD1MINI
//#define IMU_ROTATION DEG_0
//#define SECOND_IMU_ROTATION DEG_90

#define PRIMARY_IMU_OPTIONAL false
#define SECONDARY_IMU_OPTIONAL true

#if MY_IMU_ROTATION == 0
#define IMU_ROTATION DEG_0
#elif MY_IMU_ROTATION == 90
#define IMU_ROTATION DEG_90
#elif MY_IMU_ROTATION == 180
#define IMU_ROTATION DEG_180
#elif MY_IMU_ROTATION == 270
#define IMU_ROTATION DEG_270
#endif

#if MY_SECOND_IMU_ROTATION == 0
#define SECOND_IMU_ROTATION DEG_0
#elif MY_SECOND_IMU_ROTATION == 90
#define SECOND_IMU_ROTATION DEG_90
#elif MY_SECOND_IMU_ROTATION == 180
#define SECOND_IMU_ROTATION DEG_180
#elif MY_SECOND_IMU_ROTATION == 270
#define SECOND_IMU_ROTATION DEG_270
#endif

#if MY_IMU_COUNT == 1
#define MAX_IMU_COUNT 1

#ifndef IMU_DESC_LIST
#define IMU_DESC_LIST \
    IMU_DESC_ENTRY(IMU,        PRIMARY_IMU_ADDRESS_ONE,   IMU_ROTATION,        PIN_IMU_SCL, PIN_IMU_SDA, PRIMARY_IMU_OPTIONAL,   PIN_IMU_INT) 

#endif
#endif

#if MY_IMU_COUNT == 2
#define MAX_IMU_COUNT 2

#ifndef IMU_DESC_LIST
#define IMU_DESC_LIST \
    IMU_DESC_ENTRY(IMU,        PRIMARY_IMU_ADDRESS_ONE,   IMU_ROTATION,        PIN_IMU_SCL, PIN_IMU_SDA, PRIMARY_IMU_OPTIONAL,   PIN_IMU_INT) \
    IMU_DESC_ENTRY(SECOND_IMU, SECONDARY_IMU_ADDRESS_TWO, SECOND_IMU_ROTATION, PIN_IMU_SCL, PIN_IMU_SDA, SECONDARY_IMU_OPTIONAL, PIN_IMU_INT_2)
#endif
#endif

// Battery monitoring options (comment to disable):
// BAT_EXTERNAL for ADC pin, BAT_INTERNAL for internal - can detect only low battery, BAT_MCP3021 for external ADC
#define BATTERY_MONITOR BAT_EXTERNAL
#define BATTERY_SHIELD_RESISTANCE 180 //130k BatteryShield, 180k SlimeVR or fill in external resistor value in kOhm

#define PIN_IMU_SDA D2
#define PIN_IMU_SCL D1
#define PIN_IMU_INT D5
#define PIN_IMU_INT_2 D6
#define PIN_BATTERY_LEVEL A0

